version: '3.8'
services:
  self-test:
    image: chronollm/sn38-validator@sha256:12e9b1637eed49c6758fc780af3fedfbab4781a768f8f78dbc6c913b2ed76737

    restart: "on-failure"
    ports:
      - "8081:8081"
    environment:
      - WALLET_NAME=miner
      - BACKEND_URL=https://api.chronollm.com
      # This secret is encrypted client-side by Phala CLI before transmission
      - HOTKEY_FILE_CONTENT=${HOTKEY_FILE_CONTENT}
      - HF_TOKEN=${HF_TOKEN}
      - HF_REPO=${HF_REPO}
    command: ["python", "-m", "sn38.neurons.miner_leak_test", "--repo", "${HF_REPO}"]
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - self-test-cache:/tmp/model-cache

volumes:
  self-test-cache:
