version: '3.8'
services:
  validator:
    image: chronollm/sn38-validator@sha256:9107b322c81e46eb8f3076d15dee861d738d9cba1888f226b5c2988b9d2afaab

    restart: "on-failure"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - validator-data:/app/data
    environment:
      - NETUID=38
      - SUBTENSOR_NETWORK=finney
      - BACKEND_URL=https://api.chronollm.com
      # This secret is encrypted client-side by Phala CLI before transmission
      - WALLET_NAME=validator
      - HOTKEY_FILE_CONTENT=${HOTKEY_FILE_CONTENT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - HF_DEBUG=${HF_DEBUG:-0}
    command: ["python", "-m", "sn38.neurons.validator"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  validator-data: